# Default logging level for SLF4J simple logger
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false
org.slf4j.simpleLogger.log.io.netty=error
org.slf4j.simpleLogger.log.org.littleshoot=error
org.slf4j.simpleLogger.log.com.browserup=warn
